### ISSUE TITLE
Rename "get()" function

### ISSUE THREAD

**Issue by DerLeole** [D2klaas/Godot-4-HTTPManager#12]
Starting from Godot 4.2 (might be earlier than that) the `get()` function in the `HTTPManagerJob` class throws the following error:

> Parse Error: The method "get()" overrides a method from native class "Object". This won't be called by the engine and may not work as expected. (Warning treated as error.)

While it is technically a Warning (only treated as an error) the `get()` function included in this Addon, can never be called, as long as it is named that.

I propose a simple name to something like `httpget()`. 

This ofc also requires updates to the docs and readme.

Thanks a lot for this!

**Comment by D2klaas** [comment]
Hi, never thought about that issue .... but you are right.
Well the naming "httpget" implies that the call is "GET" but it also performace "POST" calls.

Since "call" is taken i may rename it "fetch" wich doesn't collide with the usual godot namings.

Thanks for your help!
