### ISSUE TITLE
Doesn't work inside custom plugin script

### ISSUE THREAD

**Issue by tamtakoe** [D2klaas/Godot-4-HTTPManager#13]
` Invalid get index 'job' (on base: 'Node (HTTPManager)').` if `Engine.is_editor_hint() == true`

**Comment by D2klaas** [comment]
Hi,
can you provide more information on how you use it? Do you want to use it in tool mode in an other plugin?

**Comment by tamtakoe** [comment]
Yes. If I use e.g. your HTTPManager-example.gd with @tool annotation in my plugin I have the error

**Comment by D2klaas** [comment]
The HTTPManager is itself not a @tool script, therefore it does not provide any "runtime" functionality. Furthermore it is supposed to reside as a node in a tree to get the process calls. But if you have any controls (e.g. a panel anywhere) you could use it there because it is then part of a tree.

**Comment by tamtakoe** [comment]
As I know HTTPManager shouldn't be a tool script... But maybe it is because of https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#editing-variables

> Code from other nodes doesn't run in the editor. Your access to other nodes is limited. You can access the tree and nodes, and their default properties, but you can't access user variables. If you want to do so, other nodes have to run in the editor too. Autoload nodes cannot be accessed in the editor at all.

Do we have some way to use HTTPManager in the editor mode?

**Comment by D2klaas** [comment]
Yes, because it is no toolscript it will not be initialized, therefore its members are not accessible.

The only way seems to be to add @tool to all classes. Have you tried this?

**Comment by tamtakoe** [comment]
I just tried it. It works now! Does it possible to add @tool for github project?

**Comment by D2klaas** [comment]
I'm not sure if this has any drawbacks to the functionality. This must be tested first.

I will consider this if i have more time to test it. For now i will close this issue since its not realy an issue but more of a missfited usecase.

**Comment by tamtakoe** [comment]
Ok, thx. I hope @tool can't be affect the editor. Any way you can switch on tool mode by a checkbox in the plugin settings or allow to use HTTP manager without Node (by extending HTTPManager.gd etc.)

**Comment by D2klaas** [comment]
> Any way you can switch on tool mode by a checkbox in the plugin settings

How would you do that?
