### ISSUE TITLE
mime type images/* doesn't work

### ISSUE THREAD

**Issue by tamtakoe** [D2klaas/Godot-4-HTTPManager#14]
```py
$HTTPManager.job("https://cdn2.thecatapi.com/images/ld.jpg").mime("image/*").on_success(self.onComplete).fetch()
```
make the error:
```sh
HTTPManager: starting request https://cdn2.thecatapi.com/images/ld.jpg
res://addons/HTTPManager/classes/HTTPManagerJob.gd:304 - Invalid operands 'Nil' and 'String' in operator '+'.
```
Looks like incorrect logic of choosing between `response_mime` and `forced_mime`

**Comment by D2klaas** [comment]
Hi,
there was an error in HTTPManagerJob. I've fixed it now and an error will be thrown when mime-type is invalid. BEcause mime("image/*") is not a valid Mimetype. You better use mime("image/unknown") or some thing as only word characters are allowed.

**Comment by tamtakoe** [comment]
Thx! Do you plan to fix it in the README?
