### ISSUE TITLE
How to use the plugin without node?

### ISSUE THREAD

**Issue by tamtakoe** [D2klaas/Godot-4-HTTPManager#15]
I try to setup HTTPManager this way
```py
var httpManager = HTTPManager.new()
httpManager.print_debug = true
httpManager._ready()
```
but get the error
```
 Timer was not added to the SceneTree. Either add it or set autostart to true.
```

**Comment by D2klaas** [comment]
HTTPManager is made to be a node in a tree.

```
var httpManager = HTTPManager.new()
get_tree().current_scene.add_child(httpManager )
httpManager.print_debug = true

```

... should do it. You can not use it outside a tree.

**Comment by tamtakoe** [comment]
I have no `get_tree()` inside my script(

Can you implement this kind of usage? It's a really strange architecture when an HTTP service has a tightly bound UI. It would be much better if we had some kind of core service that could be run anywhere.

**Comment by D2klaas** [comment]
HTTPManager is based on HTTPRequest wich is a node. It will not work if not in a tree, it will not receive _proccess if not in a tree.

Why do you have no get_tree()? where do you use it? You know that all plugins also receide in the tree but heigher up so you dont see them in your project?

**Comment by tamtakoe** [comment]
I use it inside script extended by `EditorInspectorPlugin`

**Comment by D2klaas** [comment]
As far as i know you need a editorPlugin to install a EditorInspectorPlugin. EditorPlugin is itself a node in the tree. If you instanciate the HTTPManager in the plugin and hand the handle over to the InspectorPlugin this should do the trick.

**Comment by tamtakoe** [comment]
Works!
```py
...
plugin = preload("node_inspector.gd").new(self)
plugin.httpManager = dock.get_node("HTTPManager")
```
Looks like we need to inject HTTP-service from UI-level of our application any time... Not good if I want to do some network work in background

**Comment by D2klaas** [comment]
Does this work? Since EditorPlugin is a node it must have add-child. After instancing InspectorPlugin you could just. If you already store plugin in InspectorPlugin you could just plugin.hm.do()

```
hm = HTTPManager.new()
add_child(hm)
plugin = preload("node_inspector.gd").new(self)
plugin.httpmanager = hm
```

**Comment by tamtakoe** [comment]
Also works. In this case we are using new instance of HTTP-manager (another one we have inside our plugin scene). So if we have plugin UI with dock its make sense to use dock instance of HTTP-manager

**Comment by D2klaas** [comment]
So, i see this "issue" as resolved. Godots core philosophy is based on nodes in a scenetree,
