### ISSUE TITLE
Request for PATCH and DELETE jobs

### ISSUE THREAD

**Issue by supadeveloper** [D2klaas/Godot-4-HTTPManager#5]
Hi, it would be nice if there were options to add variables for PATCH and DELETE requests! I'm looking to use this addon but currently I need to use delete patch requests with json body to an endpoint. Would I be able to do these types of requests with this addon?

**Comment by D2klaas** [comment]
Hi, been busy the days and didn't see your suggestion.
I added the method( method:int ) method. Now you should be able to specifiy a specific method for your request like DELETE or PATCH.
Let me know if this fits your needs!

**Comment by supadeveloper** [comment]
Thank you! It fits my needs perfectly.
