### ISSUE TITLE
All values are being converted to strings

### ISSUE THREAD

**Issue by soccerob** [D2klaas/Godot-4-HTTPManager#8]
I believe the Content-Type of the requests are converting my post parameters from a valid JSON to string values. For example, when I use the built-in HTTPRequest node and I include an integer or an array, this add-on is converting those values from JSON objects into String values.

The following is an example of the payload being received on my server with the HTTPRequest node:
```
{
"id": 1,
"marked": [
1,
2,
3,
4,
5,
56
]
}
```

And here is the format of the same parameters when using the HTTPManager class:
```
{
"id": "1",
"marked": "[1,2,3,4,5,56]"
}
```

I have tried changing the content-type in the HTTPPipe.gd file from "application/x-www-form-urlencoded; charset=utf-8" to "application/json" but it doesn't like that, I imagine because the UTF-8 conversions are causing an issue but I am not familiar enough with that stuff to determine if that's the issue or figure out how to fix it. 

Any thoughts on how I could use standard json with this add-on?

**Comment by D2klaas** [comment]
Hi,
can you provide me the part of the code where you add the post-data to the request?
It must be something like ...
`.add_post("data", JSON.stringify([1,2,3,4,54]))`

**Comment by soccerob** [comment]
```
func get_marked_spots() -> PackedInt32Array:
	var values:PackedInt32Array = []
	for grid in grids:
		if grid.is_marked:
			values.push_back(grid.value)
	return values
func get_free_spots() -> PackedInt32Array:
	var values:PackedInt32Array = []
	for grid in grids:
		if grid.is_marked and grid.is_free_daub:
			values.push_back(grid.value)
	return values

var params:Dictionary = {}
params.game = data.id
params.card = card.data.id
params.marks = card.get_marked_spots()
params.free = card.get_free_spots()
print(params)
**
## output: 
## { "game": 20897, "card": 603749, "marks": [8, 5, 3, 12, 14, 21, 29, 28, 30, 25, 37, 39, 45, 34, 47, 54, 51, 52, 57, 67, 61, 68, 69, 72], "free": [3,12] }
**
_manager = $HTTPManager
_manager.display_progress = false
_manager.job(
	server_endpoint
).add_post(
	params
).on_success(
	_on_complete
).on_failure(
	_on_error
).get()
```

**Comment by D2klaas** [comment]
Ah, i see! 
There is no automatic json encoding of post or get data, you have to do this on your own.
Basicly all request data in HTTP communication must be translated to text. HTTPManager only ensures that the string is then url encoded. If you feed the add_post function with any other then a string godot will do some sort of typecasting. This isnt a problem with integer or floats but complex objects like dictionarys or arrays will be broken.

If you:

```
_manager = $HTTPManager
_manager.display_progress = false
_manager.job(
	server_endpoint
).add_post(
	"myjson", JSON.stringify(params) #<---- here your data gets JSON encoded and send with the name myjson
).on_success(
	_on_complete
).on_failure(
	_on_error
).get()

```

if you have PHP working on the other side you could then ...

`$params = json_decode($_POST['myjson']);`

... to decode

**Comment by soccerob** [comment]
Hmmm, is there a reason that every post value is getting encoded as a string? It should be able to send arrays, integers, floats, etc. as raw values, and just encode text as a string when it is already a string. Is there a way to prevent the string conversions and just submit the raw data?

**Comment by soccerob** [comment]
I believe I was able to get this working properly by changing some lines in HTTPPipe.gd (lines 81-84):

```
	elif job.request_post.size() > 0:
		var raw_data = JSON.stringify(job.request_post)
		job.add_header("Content-Type", "application/json")
		job.add_header("Content-Length", str(len(raw_data)))
		body = raw_data.to_utf8_buffer()
```

Note: I'm using this class strictly for api requests, not for downloading any images or any of the other behaviors you have created. I have still tested some of the functionality and it appears to be working just fine.

**Comment by D2klaas** [comment]
Good if this works for you! But i don't see this as an issue ... this is s special use case. I will leave the manager as it is to be standard compliant and close this "issue".
